title: "A day in the life of a rubber ducky"
author: "Dave Bakker"
description: "Blogging because the cool kids do it too..."

#email: "example@mail.com"
github_username: "badeend"

theme: "minima"
markdown: GFM
rss: rss
 
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true
